import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import RootLayoutComp from "@/layouts/RootLayout";
import { AuthProvider } from "@/components";
import { inter } from "@/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <RootLayoutComp>{children}</RootLayoutComp>
        </body>
      </html>
    </AuthProvider>
  );
}
